global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
  
  - job_name: 'loki'
    dns_sd_configs:
      - names:
          - loki-read
          - loki-write
          - loki-backend
        type: A
        port: 3100
  
  - job_name: 'promtail'
    dns_sd_configs:
      - names:
          - promtail
        type: A
        port: 9080

  - job_name: 'nono-events-metrics-new'
    # metrics_path defaults to /metrics
    metrics_path: '/metrics/new'
    static_configs:
      - targets: ['api.nono-events.de']
        labels:
          instance: 'nono-events-new'

  - job_name: 'nono-events-metrics'
    # metrics_path defaults to /metrics, so it's explicitly defined here for clarity
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api.nono-events.de']
        labels:
          instance: 'nono-events-old'
